$LOAD_PATH.unshift(File.expand_path(File.dirname(".")))
# $LOAD_PATH.unshift(File.expand_path(File.dirname("./src")))
require 'rake/testtask'
require 'rake/clean'
require 'fileutils'

task :default => :test

task :test do
    Rake::TestTask.new do |t|
        t.libs << "src"
        t.test_files = FileList['test/*.rb']
        t.verbose = true
    end
end
